version: '3.8'

services:
  # RabbitMQ Service
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"   # RabbitMQ messaging port
      - "15672:15672" # RabbitMQ management UI
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword

  # Order Service
  order-service:
    image: "serpild/order-service"
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_CONNECTION_STRING=amqp://myuser:mypassword@rabbitmq:5672/
      - PORT=3000
    depends_on:
      - rabbitmq

  # Product Service
  product-service:
    image: "serpild/product-service"
    ports:
      - "3030:3030"
    environment:
      - PORT=3030

  # Store Front (Frontend Service)
  store-front:
    image: serpild/store-front-l8:latest
    ports:
      - "80:80"
    environment:
      - VUE_APP_ORDER_SERVICE_URL=http://order-service:3000
      - VUE_APP_PRODUCT_SERVICE_URL=http://product-service:3030
    depends_on:
      - order-service
      - product-service

 

